// Code generated by the Lingua Franca compiler from:
// file://Users/yanghuang/Projects/cs267/benchmarks-lingua-franca/C/Savina/src/parallelism/NQueens.lf
#define LOG_LEVEL 1
#define TARGET_FILES_DIRECTORY "/Users/yanghuang/Projects/cs267/benchmarks-lingua-franca/C/Savina/src-gen/parallelism/NQueens"
#include "ctarget/ctarget.h"
#include "core/reactor.c"
#include "core/mixed_radix.h"
#include "deque.h"
typedef struct work_item_t {
    size_t *data;
    size_t depth;
} work_item_t;

typedef deque_t work_queue_t;

/**
 * Checks whether the board is a valid configuration of queens where no two queens are on the same 
 * straight or diagonal line.
 */
int board_valid(size_t n, size_t *a) {
    size_t p = 0, q = 0;
    size_t x = 0, y = 0;
    for (x = 0; x < n; x++) {
        p = a[x];
        for (y = x + 1; y < n; y++) {
            q = a[y];
            if (q == p || q == p - (y - x) || q == p + (y - x)) {
                return false;
            }
        }
    }
    return true;
}

/**
 * Function to recursively solve the problem. Called inside the Worker reactor when depth is greater than 
 * or equal to "threshold" (parameter passed in to the benchmark)
 */
size_t nqueens_kernel_seq(size_t *a, size_t depth, size_t size) {
    if(size == depth) {
        return 1;
    }
    size_t num_solutions = 0;
    size_t *b = (size_t *) malloc (sizeof(size_t) * (depth + 1));
    size_t cnt = 0;
    // recursive calls
    while (cnt < size) {
        size_t idx = 0;
        
        // copy current configuration into new array b and set next row to contain a queen
        // at position "cnt"
        for (idx = 0; idx < depth + 1; idx++) {
            b[idx] = a[idx];
        }
        // set 
        b[depth] = cnt;
        // if new configuration is valid call nqueens_kernel_seq on the new configuration
        if (board_valid(depth + 1, b)) {
            num_solutions += nqueens_kernel_seq(b, depth + 1, size);
        }
        cnt++;
    }
    free(b);
    return num_solutions;
}
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
// =============== START reactor class BenchmarkRunner
// *********** From the preamble, verbatim:
static double toMS(interval_t t) {
    return t / 1000000.0;
}

int comp (const void * elem1, const void * elem2) {
    int f = *((double*)elem1);
    int s = *((double*)elem2);
    if (f > s) return  1;
    if (f < s) return -1;
    return 0;
}

static double median(double* execTimes, int size) {
    if (size == 0) {
        return 0.0;
    }
    
    int middle = size / 2;
    if(size % 2 == 1) {
        return execTimes[middle];
    } else {
        return (execTimes[middle-1] + execTimes[middle]) / 2;
    }
}

static double* getMSMeasurements(interval_t* measured_times, int num_iterations) {
    
    double* msMeasurements = (double *) calloc(num_iterations, sizeof(double));
    for (int i = 0; i < num_iterations; i++) {
        msMeasurements[i] = toMS(measured_times[i]);
    }
    
    return msMeasurements;
}
    

// *********** End of preamble.
// *********** From the preamble, verbatim:
void printBenchmarkInfo(char* benchmarkId) {
    printf("Benchmark: %s\n", benchmarkId);
}

void printSystemInfo() {
    
    printf("System information\n"); 
    printf("O/S Name: ");
    
    #ifdef _WIN32
    printf("Windows 32-bit");
    #elif _WIN64
    printf("Windows 64-bit");
    #elif __APPLE__ || __MACH__
    printf("Mac OSX");
    #elif __linux__
    printf("Linux");
    #elif __FreeBSD__
    printf("FreeBSD");
    #elif __unix || __unix__
    printf("Unix");
    #else
    printf("Other");
    #endif
    
    printf("\n");
}
    

// *********** End of preamble.
typedef struct {
    bool value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} benchmarkrunner_inStart_t;
typedef struct {
    bool value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} benchmarkrunner_finish_t;
typedef struct {
    bool value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} benchmarkrunner_start_t;
typedef struct {
    trigger_t* trigger;
    bool value;
    bool is_present;
    bool has_value;
    lf_token_t* token;
    
} benchmarkrunner_nextIteration_t;
typedef struct {
    trigger_t* trigger;
    bool value;
    bool is_present;
    bool has_value;
    lf_token_t* token;
    
} benchmarkrunner_done_t;
typedef struct {
    struct self_base_t base;
    int num_iterations;
    unsigned count;
    instant_t startTime;
    interval_t* measuredTimes;
    benchmarkrunner_nextIteration_t _lf_nextIteration;
    benchmarkrunner_done_t _lf_done;
    benchmarkrunner_inStart_t* _lf_inStart;
    // width of -2 indicates that it is not a multiport.
    int _lf_inStart_width;
    // Default input (in case it does not get connected)
    benchmarkrunner_inStart_t _lf_default__inStart;
    benchmarkrunner_finish_t* _lf_finish;
    // width of -2 indicates that it is not a multiport.
    int _lf_finish_width;
    // Default input (in case it does not get connected)
    benchmarkrunner_finish_t _lf_default__finish;
    benchmarkrunner_start_t _lf_start;
    int _lf_start_width;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    reaction_t _lf__reaction_2;
    reaction_t _lf__reaction_3;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
    trigger_t _lf__nextIteration;
    reaction_t* _lf__nextIteration_reactions[1];
    trigger_t _lf__done;
    reaction_t* _lf__done_reactions[1];
    trigger_t _lf__inStart;
    trigger_t _lf__finish;
    reaction_t* _lf__finish_reactions[1];
} benchmarkrunner_self_t;
#include "ctarget/set.h"
void benchmarkrunnerreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    benchmarkrunner_self_t* self = (benchmarkrunner_self_t*)instance_args;
    benchmarkrunner_nextIteration_t* nextIteration = &self->_lf_nextIteration;
    #pragma GCC diagnostic pop
    // Initialize an array of interval_t
    self->measuredTimes = (interval_t *) calloc(self->num_iterations, sizeof(interval_t));
    schedule(nextIteration, 0);
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void benchmarkrunnerreaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    benchmarkrunner_self_t* self = (benchmarkrunner_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    benchmarkrunner_nextIteration_t* nextIteration = &self->_lf_nextIteration;
    // Set the fields of the action struct to match the current trigger.
    nextIteration->is_present = (bool)self->_lf__nextIteration.status;
    nextIteration->has_value = ((self->_lf__nextIteration.token) != NULL && (self->_lf__nextIteration.token)->value != NULL);
    nextIteration->token = (self->_lf__nextIteration.token);
    if (nextIteration->has_value) {
        nextIteration->value = *(bool*)(self->_lf__nextIteration.token)->value;
    }
    benchmarkrunner_start_t* start = &self->_lf_start;
    benchmarkrunner_done_t* done = &self->_lf_done;
    #pragma GCC diagnostic pop
    if (self->count < self->num_iterations) { 
        self->startTime = get_physical_time();
        SET(start, true);
    } else {
        schedule(done, 0);
    }
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void benchmarkrunnerreaction_function_2(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    benchmarkrunner_self_t* self = (benchmarkrunner_self_t*)instance_args;
    benchmarkrunner_finish_t* finish = self->_lf_finish;
    int finish_width = self->_lf_finish_width;
    benchmarkrunner_nextIteration_t* nextIteration = &self->_lf_nextIteration;
    #pragma GCC diagnostic pop
    interval_t end_time = get_physical_time();
    interval_t duration = end_time - self->startTime;
    self->measuredTimes[self->count] = duration;
    self->count += 1;
    
    printf("Iteration %d - %.3f ms\n", self->count, toMS(duration));
    
    schedule(nextIteration, 0);
    
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void benchmarkrunnerreaction_function_3(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    benchmarkrunner_self_t* self = (benchmarkrunner_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    benchmarkrunner_done_t* done = &self->_lf_done;
    // Set the fields of the action struct to match the current trigger.
    done->is_present = (bool)self->_lf__done.status;
    done->has_value = ((self->_lf__done.token) != NULL && (self->_lf__done.token)->value != NULL);
    done->token = (self->_lf__done.token);
    if (done->has_value) {
        done->value = *(bool*)(self->_lf__done.token)->value;
    }
    #pragma GCC diagnostic pop
    double* measuredMSTimes = getMSMeasurements(self->measuredTimes, self->num_iterations);
    qsort(measuredMSTimes, self->num_iterations, sizeof(double), comp);
    
    printf("Execution - Summary:\n");
    printf("Best Time:\t %.3f msec\n", measuredMSTimes[0]);
    printf("Worst Time:\t %.3f msec\n", measuredMSTimes[self->num_iterations - 1]);
    printf("Median Time:\t %.3f msec\n", median(measuredMSTimes, self->num_iterations));
    request_stop();
        
}
#include "ctarget/set_undef.h"
benchmarkrunner_self_t* new_BenchmarkRunner() {
    benchmarkrunner_self_t* self = (benchmarkrunner_self_t*)_lf_new_reactor(sizeof(benchmarkrunner_self_t));
    self->_lf_nextIteration.trigger = &self->_lf__nextIteration;
    self->_lf_done.trigger = &self->_lf__done;
    // Set input by default to an always absent default input.
    self->_lf_inStart = &self->_lf_default__inStart;
    // Set input by default to an always absent default input.
    self->_lf_finish = &self->_lf_default__finish;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = benchmarkrunnerreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = benchmarkrunnerreaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "?";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__reaction_2.number = 2;
    self->_lf__reaction_2.function = benchmarkrunnerreaction_function_2;
    self->_lf__reaction_2.self = self;
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    self->_lf__reaction_2.STP_handler = NULL;
    self->_lf__reaction_2.name = "?";
    self->_lf__reaction_2.mode = NULL;
    self->_lf__reaction_3.number = 3;
    self->_lf__reaction_3.function = benchmarkrunnerreaction_function_3;
    self->_lf__reaction_3.self = self;
    self->_lf__reaction_3.deadline_violation_handler = NULL;
    self->_lf__reaction_3.STP_handler = NULL;
    self->_lf__reaction_3.name = "?";
    self->_lf__reaction_3.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    self->_lf__nextIteration.last = NULL;
    self->_lf__nextIteration_reactions[0] = &self->_lf__reaction_1;
    self->_lf__nextIteration.reactions = &self->_lf__nextIteration_reactions[0];
    self->_lf__nextIteration.number_of_reactions = 1;
    self->_lf__nextIteration.is_physical = false;
    
    self->_lf__nextIteration.element_size = sizeof(bool);
    self->_lf__done.last = NULL;
    self->_lf__done_reactions[0] = &self->_lf__reaction_3;
    self->_lf__done.reactions = &self->_lf__done_reactions[0];
    self->_lf__done.number_of_reactions = 1;
    self->_lf__done.is_physical = false;
    
    self->_lf__done.element_size = sizeof(bool);
    self->_lf__inStart.last = NULL;
    self->_lf__inStart.element_size = sizeof(bool);
    self->_lf__finish.last = NULL;
    self->_lf__finish_reactions[0] = &self->_lf__reaction_2;
    self->_lf__finish.reactions = &self->_lf__finish_reactions[0];
    self->_lf__finish.number_of_reactions = 1;
    self->_lf__finish.element_size = sizeof(bool);
    return self;
}
// =============== END reactor class BenchmarkRunner

// =============== START reactor class Manager
typedef struct {
    size_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} manager_solutions_found_t;
typedef struct {
    work_queue_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} manager_more_work_t;
typedef struct {
    bool value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} manager_start_t;
typedef struct {
    work_item_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} manager_do_work_t;
typedef struct {
    bool value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} manager_finished_t;
typedef struct {
    trigger_t* trigger;
    
    bool is_present;
    bool has_value;
    lf_token_t* token;
    
} manager_next_t;
typedef struct {
    trigger_t* trigger;
    
    bool is_present;
    bool has_value;
    lf_token_t* token;
    
} manager_done_t;
typedef struct {
    struct self_base_t base;
    size_t num_workers;
    size_t solutions_limit;
    size_t size;
    size_t num_solutions;
    work_queue_t * manager_work_queue;
    manager_next_t _lf_next;
    manager_done_t _lf_done;
    // Multiport input array will be malloc'd later.
    manager_solutions_found_t** _lf_solutions_found;
    int _lf_solutions_found_width;
    // Default input (in case it does not get connected)
    manager_solutions_found_t _lf_default__solutions_found;
    // Multiport input array will be malloc'd later.
    manager_more_work_t** _lf_more_work;
    int _lf_more_work_width;
    // Default input (in case it does not get connected)
    manager_more_work_t _lf_default__more_work;
    manager_start_t* _lf_start;
    // width of -2 indicates that it is not a multiport.
    int _lf_start_width;
    // Default input (in case it does not get connected)
    manager_start_t _lf_default__start;
    // Array of output ports.
    manager_do_work_t* _lf_do_work;
    int _lf_do_work_width;
    // An array of pointers to the individual ports. Useful
    // for the lf_set macros to work out-of-the-box for
    // multiports in the body of reactions because their 
    // value can be accessed via a -> operator (e.g.,foo[i]->value).
    // So we have to handle multiports specially here a construct that
    // array of pointers.
    manager_do_work_t** _lf_do_work_pointers;
    manager_finished_t _lf_finished;
    int _lf_finished_width;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    reaction_t _lf__reaction_2;
    reaction_t _lf__reaction_3;
    reaction_t _lf__reaction_4;
    trigger_t _lf__next;
    reaction_t* _lf__next_reactions[1];
    trigger_t _lf__done;
    reaction_t* _lf__done_reactions[1];
    trigger_t _lf__solutions_found;
    reaction_t* _lf__solutions_found_reactions[1];
    trigger_t _lf__more_work;
    reaction_t* _lf__more_work_reactions[1];
    trigger_t _lf__start;
    reaction_t* _lf__start_reactions[1];
} manager_self_t;
#include "ctarget/set.h"
void managerreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    manager_self_t* self = (manager_self_t*)instance_args;
    manager_start_t* start = self->_lf_start;
    int start_width = self->_lf_start_width;
    int do_work_width = self->_lf_do_work_width;
    manager_do_work_t** do_work = self->_lf_do_work_pointers;
    manager_next_t* next = &self->_lf_next;
    #pragma GCC diagnostic pop
    self->manager_work_queue = (work_queue_t *) calloc(1, sizeof(struct deque_t)); // freed in shutdown reaction
    
    // set local state
    self->num_solutions = 0;
    
    // start execution
    work_item_t* item = (work_item_t *) calloc(1, sizeof(struct work_item_t)); // freed when item is passed into Worker (line 191)
    
    deque_push_back(self->manager_work_queue, item); 
    
    schedule(next, 0);
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void managerreaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    manager_self_t* self = (manager_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    manager_done_t* done = &self->_lf_done;
    // Set the fields of the action struct to match the current trigger.
    done->is_present = (bool)self->_lf__done.status;
    done->has_value = ((self->_lf__done.token) != NULL && (self->_lf__done.token)->value != NULL);
    done->token = (self->_lf__done.token);
    manager_finished_t* finished = &self->_lf_finished;
    #pragma GCC diagnostic pop
    // expected solutions for various problem sizes
    size_t solutions[] = {
        1,
        0,
        0,
        2,
        10,     /* 5 */
        4,
        40,
        92,
        352,
        724,    /* 10 */
        2680,
        14200,
        73712,
        365596,
        2279184, /* 15 */
        14772512,
        95815104,
        666090624,
        4968057848,
        39029188884 /* 20 */
    };
    
    // validate the result
    size_t expected = solutions[self->size-1];
    bool valid = self->num_solutions == expected;
    if (self->solutions_limit < expected) {
        valid = self->num_solutions >= self->solutions_limit && self->num_solutions <= expected;
    }
    
    // The validation check above is a corrected version. The original Savina implementation will
    // wrongly mark results as invalid if the solutions limit is above the expected solution.
    if (!valid) {
        error_print_and_exit(
            "An invalid number of solutions was computed: %ld.\n", self->num_solutions
        );
    }
    free(self->manager_work_queue);
    SET(finished, true);
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void managerreaction_function_2(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    manager_self_t* self = (manager_self_t*)instance_args;
    // Expose the action struct as a local variable whose name matches the action name.
    manager_next_t* next = &self->_lf_next;
    // Set the fields of the action struct to match the current trigger.
    next->is_present = (bool)self->_lf__next.status;
    next->has_value = ((self->_lf__next.token) != NULL && (self->_lf__next.token)->value != NULL);
    next->token = (self->_lf__next.token);
    manager_done_t* done = &self->_lf_done;
    int do_work_width = self->_lf_do_work_width;
    manager_do_work_t** do_work = self->_lf_do_work_pointers;
    #pragma GCC diagnostic pop
    if (deque_is_empty(self->manager_work_queue)) {
        // we are done if there is no more work
        schedule(done, 0);
    } else {
        // send a work item to each worker (until there is no more work)
        for (int i = 0; i < self->num_workers && !deque_is_empty(self->manager_work_queue); i++) {
            work_item_t *val = deque_pop_front(self->manager_work_queue);
            SET(do_work[i], *val);
            free(val);
        }
        // and schedule the next iteration
        schedule(next, 0);
    }
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void managerreaction_function_3(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    manager_self_t* self = (manager_self_t*)instance_args;
    manager_solutions_found_t** solutions_found = self->_lf_solutions_found;
    int solutions_found_width = self->_lf_solutions_found_width;
    #pragma GCC diagnostic pop
    // accumulate all the solutions found by looping through solutions_found and increment num_solutions
    size_t s = 0;
    
    for (int i = 0; i < self->num_workers; i++) {
        if(solutions_found[i]->is_present) {
            s += solutions_found[i]->value;
        }
    }
    if (s > 0) {
        self->num_solutions += s;
        info_print(" Found %zu solutions; Total solutions %zu\n", s, self->num_solutions);
    }
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void managerreaction_function_4(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    manager_self_t* self = (manager_self_t*)instance_args;
    manager_more_work_t** more_work = self->_lf_more_work;
    int more_work_width = self->_lf_more_work_width;
    #pragma GCC diagnostic pop
    // append all work items received from the workers to the internal work queue
    for (int i = 0; i < self->num_workers; i++) {
        if (more_work[i]->is_present) {
            work_queue_t items = more_work[i]->value;
            while (!deque_is_empty(&items)) {
                deque_push_back(self->manager_work_queue, deque_pop_front(&items));
            }
        }
    }
        
}
#include "ctarget/set_undef.h"
manager_self_t* new_Manager() {
    manager_self_t* self = (manager_self_t*)_lf_new_reactor(sizeof(manager_self_t));
    self->_lf_next.trigger = &self->_lf__next;
    self->_lf_done.trigger = &self->_lf__done;
    // Set input by default to an always absent default input.
    self->_lf_start = &self->_lf_default__start;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = managerreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = managerreaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "?";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__reaction_2.number = 2;
    self->_lf__reaction_2.function = managerreaction_function_2;
    self->_lf__reaction_2.self = self;
    self->_lf__reaction_2.deadline_violation_handler = NULL;
    self->_lf__reaction_2.STP_handler = NULL;
    self->_lf__reaction_2.name = "?";
    self->_lf__reaction_2.mode = NULL;
    self->_lf__reaction_3.number = 3;
    self->_lf__reaction_3.function = managerreaction_function_3;
    self->_lf__reaction_3.self = self;
    self->_lf__reaction_3.deadline_violation_handler = NULL;
    self->_lf__reaction_3.STP_handler = NULL;
    self->_lf__reaction_3.name = "?";
    self->_lf__reaction_3.mode = NULL;
    self->_lf__reaction_4.number = 4;
    self->_lf__reaction_4.function = managerreaction_function_4;
    self->_lf__reaction_4.self = self;
    self->_lf__reaction_4.deadline_violation_handler = NULL;
    self->_lf__reaction_4.STP_handler = NULL;
    self->_lf__reaction_4.name = "?";
    self->_lf__reaction_4.mode = NULL;
    self->_lf__next.last = NULL;
    self->_lf__next_reactions[0] = &self->_lf__reaction_2;
    self->_lf__next.reactions = &self->_lf__next_reactions[0];
    self->_lf__next.number_of_reactions = 1;
    self->_lf__next.is_physical = false;
    
    self->_lf__next.element_size = 0;
    self->_lf__done.last = NULL;
    self->_lf__done_reactions[0] = &self->_lf__reaction_1;
    self->_lf__done.reactions = &self->_lf__done_reactions[0];
    self->_lf__done.number_of_reactions = 1;
    self->_lf__done.is_physical = false;
    
    self->_lf__done.element_size = 0;
    self->_lf__solutions_found.last = NULL;
    self->_lf__solutions_found_reactions[0] = &self->_lf__reaction_3;
    self->_lf__solutions_found.reactions = &self->_lf__solutions_found_reactions[0];
    self->_lf__solutions_found.number_of_reactions = 1;
    self->_lf__solutions_found.element_size = sizeof(size_t);
    self->_lf__more_work.last = NULL;
    self->_lf__more_work_reactions[0] = &self->_lf__reaction_4;
    self->_lf__more_work.reactions = &self->_lf__more_work_reactions[0];
    self->_lf__more_work.number_of_reactions = 1;
    self->_lf__more_work.element_size = sizeof(work_queue_t);
    self->_lf__start.last = NULL;
    self->_lf__start_reactions[0] = &self->_lf__reaction_0;
    self->_lf__start.reactions = &self->_lf__start_reactions[0];
    self->_lf__start.number_of_reactions = 1;
    self->_lf__start.element_size = sizeof(bool);
    return self;
}
// =============== END reactor class Manager

// =============== START reactor class Worker
typedef struct {
    work_item_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} worker_do_work_t;
typedef struct {
    size_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} worker_solutions_found_t;
typedef struct {
    work_queue_t value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} worker_more_work_t;
typedef struct {
    struct self_base_t base;
    size_t bank_index;
    size_t size;
    size_t threshold;
    
    worker_do_work_t* _lf_do_work;
    // width of -2 indicates that it is not a multiport.
    int _lf_do_work_width;
    // Default input (in case it does not get connected)
    worker_do_work_t _lf_default__do_work;
    worker_solutions_found_t _lf_solutions_found;
    int _lf_solutions_found_width;
    worker_more_work_t _lf_more_work;
    int _lf_more_work_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__do_work;
    reaction_t* _lf__do_work_reactions[1];
} worker_self_t;
#include "ctarget/set.h"
void workerreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    worker_self_t* self = (worker_self_t*)instance_args;
    worker_do_work_t* do_work = self->_lf_do_work;
    int do_work_width = self->_lf_do_work_width;
    worker_solutions_found_t* solutions_found = &self->_lf_solutions_found;
    worker_more_work_t* more_work = &self->_lf_more_work;
    #pragma GCC diagnostic pop
    size_t *a = do_work->value.data;
    size_t depth = do_work->value.depth;
    
    if (self->size == depth) {
        // It is unclear when exactly this evaluates to true and what this means. 
        // However, this seems to be essential for some sizes, including size=1.
        SET(solutions_found, 1);
        // abort the reaction
        return;
    }
    
    if (depth >= self->threshold) {
        // If depth is greater or equal to the threshold, the worker searches for solutions.
        size_t num_solutions = nqueens_kernel_seq(a, depth, self->size);
        if (num_solutions > 0) {
            SET(solutions_found, num_solutions);
        }
    } else {
        // Otherwise, if depth is less than the threshold, the worker splits up the workload and
        // produces new work items.
        size_t newDepth = depth + 1;
        // prepare a work queue to be sent later
        work_queue_t *work_queue = (work_queue_t *) calloc(1, sizeof(struct deque_t)); //freed in Manager (line 225)
        for (int i = 0; i < self->size; i++) {
            // prepare a mutable work item
            size_t *vec = (size_t *) calloc(newDepth, sizeof(size_t)); // freed when the work_item_t is handled in another Worker (line 292)
            work_item_t* item = (work_item_t *) calloc(1, sizeof(struct work_item_t)); // freed when popped from manager_work_queue (line 191)
            item->data = vec;
            item->depth = newDepth;
            size_t *b = item->data;
            // copy depth items from a to b
            int j = 0;
            for (j = 0; j < depth; j++) {
                b[j] = a[j];
            }
    
            b[depth] = i;
            
            // add the item to the list if is valid
            if (board_valid(newDepth, b)) {
                deque_push_back(work_queue, item);
            }
        }
        if (!deque_is_empty(work_queue)) {
            SET(more_work, *work_queue);
        }
        free(work_queue);
    }
    
    free(a); // frees memory of current sequence
        
}
#include "ctarget/set_undef.h"
worker_self_t* new_Worker() {
    worker_self_t* self = (worker_self_t*)_lf_new_reactor(sizeof(worker_self_t));
    // Set input by default to an always absent default input.
    self->_lf_do_work = &self->_lf_default__do_work;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = workerreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__do_work.last = NULL;
    self->_lf__do_work_reactions[0] = &self->_lf__reaction_0;
    self->_lf__do_work.reactions = &self->_lf__do_work_reactions[0];
    self->_lf__do_work.number_of_reactions = 1;
    self->_lf__do_work.element_size = sizeof(work_item_t);
    return self;
}
// =============== END reactor class Worker

// =============== START reactor class NQueens
typedef struct {
    struct self_base_t base;
    size_t numIterations;
    size_t size;
    size_t threshold;
    size_t solutionsLimit;
    size_t priorities;
    size_t numWorkers;
    
    reaction_t _lf__reaction_0;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
} nqueens_self_t;
#include "ctarget/set.h"
void nqueensreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    nqueens_self_t* self = (nqueens_self_t*)instance_args;
    
    #pragma GCC diagnostic pop
    printBenchmarkInfo("NQueensLFCBenchmark");
    printSystemInfo();
        
}
#include "ctarget/set_undef.h"
nqueens_self_t* new_NQueens() {
    nqueens_self_t* self = (nqueens_self_t*)_lf_new_reactor(sizeof(nqueens_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = nqueensreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
// =============== END reactor class NQueens

char* _lf_default_argv[] = { "NQueens", "-f", "true" };
void _lf_set_default_command_line_options() {
        default_argc = 3;
        default_argv = _lf_default_argv;
}
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    _lf_tokens_with_ref_count_size = 4;
    _lf_tokens_with_ref_count = (token_present_t*)calloc(4, sizeof(token_present_t));
    if (_lf_tokens_with_ref_count == NULL) lf_print_error_and_exit("Out of memory!");
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 66;
    _lf_is_present_fields = (bool**)calloc(66, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(66, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    
    _lf_startup_reactions = (reaction_t**)calloc(2, sizeof(reaction_t*));
    _lf_startup_reactions_size = 2;
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    nqueens_self_t* nqueens_self[1];
    benchmarkrunner_self_t* nqueens_runner_self[1];
    manager_self_t* nqueens_manager_self[1];
    worker_self_t* nqueens_workers_self[20];
    // ***** Start initializing NQueens of class NQueens
    nqueens_self[0] = new_NQueens();
    int bank_index = 0;
    nqueens_self[0]->numIterations = 12;
    nqueens_self[0]->size = 12;
    nqueens_self[0]->threshold = 4;
    nqueens_self[0]->solutionsLimit = 1500000;
    nqueens_self[0]->priorities = 10;
    nqueens_self[0]->numWorkers = 20;
    _lf_startup_reactions[_lf_startup_reactions_count++] = &nqueens_self[0]->_lf__reaction_0;
    
    {
        // ***** Start initializing NQueens.runner of class BenchmarkRunner
        nqueens_runner_self[0] = new_BenchmarkRunner();
        int bank_index = 0;
        nqueens_runner_self[0]->num_iterations = nqueens_self[0]->numIterations;
        // width of -2 indicates that it is not a multiport.
        nqueens_runner_self[0]->_lf_start_width = -2;
        // width of -2 indicates that it is not a multiport.
        nqueens_runner_self[0]->_lf_inStart_width = -2;
        // width of -2 indicates that it is not a multiport.
        nqueens_runner_self[0]->_lf_finish_width = -2;
        _lf_startup_reactions[_lf_startup_reactions_count++] = &nqueens_runner_self[0]->_lf__reaction_0;
        { // For scoping
            static unsigned _initial = 0;
            nqueens_runner_self[0]->count = _initial;
        } // End scoping.
        // Initializing action NQueens.runner.nextIteration
        nqueens_runner_self[0]->_lf__nextIteration.offset = 0;
        nqueens_runner_self[0]->_lf__nextIteration.period = -1;
        nqueens_runner_self[0]->_lf__nextIteration.mode = NULL;
        // Initializing action NQueens.runner.done
        nqueens_runner_self[0]->_lf__done.offset = 0;
        nqueens_runner_self[0]->_lf__done.period = -1;
        nqueens_runner_self[0]->_lf__done.mode = NULL;
        nqueens_runner_self[0]->_lf__nextIteration.token = _lf_create_token(sizeof(bool));
        nqueens_runner_self[0]->_lf__nextIteration.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &nqueens_runner_self[0]->_lf__nextIteration.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &nqueens_runner_self[0]->_lf__nextIteration.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        nqueens_runner_self[0]->_lf__done.token = _lf_create_token(sizeof(bool));
        nqueens_runner_self[0]->_lf__done.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &nqueens_runner_self[0]->_lf__done.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &nqueens_runner_self[0]->_lf__done.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        //***** End initializing NQueens.runner
    }
    {
        // ***** Start initializing NQueens.manager of class Manager
        nqueens_manager_self[0] = new_Manager();
        int bank_index = 0;
        nqueens_manager_self[0]->num_workers = nqueens_self[0]->numWorkers;
        nqueens_manager_self[0]->solutions_limit = nqueens_self[0]->solutionsLimit;
        nqueens_manager_self[0]->size = nqueens_self[0]->size;
        nqueens_manager_self[0]->_lf_do_work_width = 20;
        // Allocate memory for multiport output.
        nqueens_manager_self[0]->_lf_do_work = (manager_do_work_t*)_lf_allocate(
                20, sizeof(manager_do_work_t),
                &nqueens_manager_self[0]->base.allocations); 
        nqueens_manager_self[0]->_lf_do_work_pointers = (manager_do_work_t**)_lf_allocate(
                20, sizeof(manager_do_work_t*),
                &nqueens_manager_self[0]->base.allocations); 
        // Assign each output port pointer to be used in
        // reactions to facilitate user access to output ports
        for(int i=0; i < 20; i++) {
                nqueens_manager_self[0]->_lf_do_work_pointers[i] = &(nqueens_manager_self[0]->_lf_do_work[i]);
        }
        // width of -2 indicates that it is not a multiport.
        nqueens_manager_self[0]->_lf_finished_width = -2;
        nqueens_manager_self[0]->_lf_solutions_found_width = 20;
        // Allocate memory for multiport inputs.
        nqueens_manager_self[0]->_lf_solutions_found = (manager_solutions_found_t**)_lf_allocate(
                20, sizeof(manager_solutions_found_t*),
                &nqueens_manager_self[0]->base.allocations); 
        // Set inputs by default to an always absent default input.
        for (int i = 0; i < 20; i++) {
            nqueens_manager_self[0]->_lf_solutions_found[i] = &nqueens_manager_self[0]->_lf_default__solutions_found;
        }
        nqueens_manager_self[0]->_lf_more_work_width = 20;
        // Allocate memory for multiport inputs.
        nqueens_manager_self[0]->_lf_more_work = (manager_more_work_t**)_lf_allocate(
                20, sizeof(manager_more_work_t*),
                &nqueens_manager_self[0]->base.allocations); 
        // Set inputs by default to an always absent default input.
        for (int i = 0; i < 20; i++) {
            nqueens_manager_self[0]->_lf_more_work[i] = &nqueens_manager_self[0]->_lf_default__more_work;
        }
        // width of -2 indicates that it is not a multiport.
        nqueens_manager_self[0]->_lf_start_width = -2;
        { // For scoping
            static size_t _initial = 0;
            nqueens_manager_self[0]->num_solutions = _initial;
        } // End scoping.
        // Initializing action NQueens.manager.next
        nqueens_manager_self[0]->_lf__next.offset = 0;
        nqueens_manager_self[0]->_lf__next.period = -1;
        nqueens_manager_self[0]->_lf__next.mode = NULL;
        // Initializing action NQueens.manager.done
        nqueens_manager_self[0]->_lf__done.offset = 0;
        nqueens_manager_self[0]->_lf__done.period = -1;
        nqueens_manager_self[0]->_lf__done.mode = NULL;
        nqueens_manager_self[0]->_lf__next.token = _lf_create_token(0);
        nqueens_manager_self[0]->_lf__next.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &nqueens_manager_self[0]->_lf__next.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &nqueens_manager_self[0]->_lf__next.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        nqueens_manager_self[0]->_lf__done.token = _lf_create_token(0);
        nqueens_manager_self[0]->_lf__done.status = absent;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].token = &nqueens_manager_self[0]->_lf__done.token;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count].status = &nqueens_manager_self[0]->_lf__done.status;
        _lf_tokens_with_ref_count[_lf_tokens_with_ref_count_count++].reset_is_present = true;
        //***** End initializing NQueens.manager
    }
    // Reactor is a bank. Iterate over bank members.
    for (int nqueens_workers_i = 0; nqueens_workers_i < 20; nqueens_workers_i++) {
        // ***** Start initializing NQueens.workers of class Worker
        nqueens_workers_self[nqueens_workers_i] = new_Worker();
        int bank_index = nqueens_workers_i;
        nqueens_workers_self[nqueens_workers_i]->bank_index = nqueens_workers_i;
        nqueens_workers_self[nqueens_workers_i]->size = nqueens_self[0]->size;
        nqueens_workers_self[nqueens_workers_i]->threshold = nqueens_self[0]->threshold;
        // width of -2 indicates that it is not a multiport.
        nqueens_workers_self[nqueens_workers_i]->_lf_solutions_found_width = -2;
        // width of -2 indicates that it is not a multiport.
        nqueens_workers_self[nqueens_workers_i]->_lf_more_work_width = -2;
        // width of -2 indicates that it is not a multiport.
        nqueens_workers_self[nqueens_workers_i]->_lf_do_work_width = -2;
        
        //***** End initializing NQueens.workers
    }
    //***** End initializing NQueens
    
    // **** Start deferred initialize for NQueens
    {
        
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of NQueens.
        nqueens_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0;
        }
        
        // ** End initialization for reaction 0 of NQueens
        
        // **** Start deferred initialize for NQueens.runner
        {
            
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of NQueens.runner.
            nqueens_runner_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 0 of NQueens.runner
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of NQueens.runner.
            nqueens_runner_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            nqueens_runner_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &nqueens_runner_self[0]->base.allocations);
            nqueens_runner_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &nqueens_runner_self[0]->base.allocations);
            nqueens_runner_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &nqueens_runner_self[0]->base.allocations);
            {
                int count = 0;
                {
                    nqueens_runner_self[0]->_lf__reaction_1.output_produced[count++] = &nqueens_runner_self[0]->_lf_start.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of NQueens.runner
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of NQueens.runner.
            nqueens_runner_self[0]->_lf__reaction_2.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 2 of NQueens.runner
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of NQueens.runner.
            nqueens_runner_self[0]->_lf__reaction_3.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 3 of NQueens.runner
            
        }
        // **** End of deferred initialize for NQueens.runner
        // **** Start deferred initialize for NQueens.manager
        {
            
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of NQueens.manager.
            nqueens_manager_self[0]->_lf__reaction_0.num_outputs = 20;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            nqueens_manager_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    20, sizeof(trigger_t**),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    20, sizeof(int),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    20, sizeof(bool*),
                    &nqueens_manager_self[0]->base.allocations);
            {
                int count = 0;
                {
                    for (int i = 0; i < 20; i++) {
                        nqueens_manager_self[0]->_lf__reaction_0.output_produced[i + count]
                                = &nqueens_manager_self[0]->_lf_do_work[i].is_present;
                    }
                    count += 20;
                }
            }
            
            // ** End initialization for reaction 0 of NQueens.manager
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of NQueens.manager.
            nqueens_manager_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            nqueens_manager_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &nqueens_manager_self[0]->base.allocations);
            {
                int count = 0;
                {
                    nqueens_manager_self[0]->_lf__reaction_1.output_produced[count++] = &nqueens_manager_self[0]->_lf_finished.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of NQueens.manager
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of NQueens.manager.
            nqueens_manager_self[0]->_lf__reaction_2.num_outputs = 20;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            nqueens_manager_self[0]->_lf__reaction_2.triggers = (trigger_t***)_lf_allocate(
                    20, sizeof(trigger_t**),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_2.triggered_sizes = (int*)_lf_allocate(
                    20, sizeof(int),
                    &nqueens_manager_self[0]->base.allocations);
            nqueens_manager_self[0]->_lf__reaction_2.output_produced = (bool**)_lf_allocate(
                    20, sizeof(bool*),
                    &nqueens_manager_self[0]->base.allocations);
            {
                int count = 0;
                {
                    for (int i = 0; i < 20; i++) {
                        nqueens_manager_self[0]->_lf__reaction_2.output_produced[i + count]
                                = &nqueens_manager_self[0]->_lf_do_work[i].is_present;
                    }
                    count += 20;
                }
            }
            
            // ** End initialization for reaction 2 of NQueens.manager
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_3 of NQueens.manager.
            nqueens_manager_self[0]->_lf__reaction_3.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 3 of NQueens.manager
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_4 of NQueens.manager.
            nqueens_manager_self[0]->_lf__reaction_4.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 4 of NQueens.manager
            
        }
        // **** End of deferred initialize for NQueens.manager
        // **** Start deferred initialize for NQueens.workers
        // Reactor is a bank. Iterate over bank members.
        for (int nqueens_workers_i = 0; nqueens_workers_i < 20; nqueens_workers_i++) {
            
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of NQueens.workers.
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    2, sizeof(trigger_t**),
                    &nqueens_workers_self[nqueens_workers_i]->base.allocations);
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    2, sizeof(int),
                    &nqueens_workers_self[nqueens_workers_i]->base.allocations);
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    2, sizeof(bool*),
                    &nqueens_workers_self[nqueens_workers_i]->base.allocations);
            {
                int count = 0;
                {
                    nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.output_produced[count++] = &nqueens_workers_self[nqueens_workers_i]->_lf_solutions_found.is_present;
                }
                {
                    nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.output_produced[count++] = &nqueens_workers_self[nqueens_workers_i]->_lf_more_work.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of NQueens.workers
            
        }
        // **** End of deferred initialize for NQueens.workers
    }
    // **** End of deferred initialize for NQueens
    // **** Start non-nested deferred initialize for NQueens
    
    
    
    // **** Start non-nested deferred initialize for NQueens.runner
    
    // For reference counting, set num_destinations for port NQueens.runner.start.
    // Iterate over range NQueens.runner.start(0,1)->[NQueens.manager.start(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        nqueens_runner_self[src_runtime]->_lf_start.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range NQueens.runner.start(0,1)->[NQueens.manager.start(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 1 of NQueens.runner triggers 1 downstream reactions
            // through port NQueens.runner.start.
            nqueens_runner_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of NQueens.runner, allocate an
            // array of trigger pointers for downstream reactions through port NQueens.runner.start
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &nqueens_runner_self[src_runtime]->base.allocations); 
            nqueens_runner_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges NQueens.runner.start(0,1)->[NQueens.manager.start(0,1)] and NQueens.manager.start(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range NQueens.manager.start(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port NQueens.manager.start's trigger struct.
                nqueens_runner_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_manager_self[dst_runtime]->_lf__start;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for NQueens.runner
    // **** Start non-nested deferred initialize for NQueens.manager
    
    // For reference counting, set num_destinations for port NQueens.manager.do_work.
    // Iterate over range NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)].
    {
        int range_start[] =  { 0, 0 };
        int range_radixes[] = { 20, 1 };
        int permutation[] = { 0, 1 };
        mixed_radix_int_t range_mr = {
            2,
            range_start,
            range_radixes,
            permutation
        };
        for (int range_count = 0; range_count < 0 + 20; range_count++) {
            int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
            int src_channel = range_mr.digits[0]; // Channel index.
            int src_bank = range_mr.digits[1]; // Bank index.
            nqueens_manager_self[src_runtime]->_lf_do_work[src_channel].num_destinations = 20;
            mixed_radix_incr(&range_mr);
        }
    }
    // For reference counting, set num_destinations for port NQueens.manager.finished.
    // Iterate over range NQueens.manager.finished(0,1)->[NQueens.runner.finish(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        nqueens_manager_self[src_runtime]->_lf_finished.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 20, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int src_channel = range_mr.digits[0]; // Channel index.
                int src_bank = range_mr.digits[1]; // Bank index.
                // Reaction 0 of NQueens.manager triggers 1 downstream reactions
                // through port NQueens.manager.do_work.
                nqueens_manager_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of NQueens.manager, allocate an
                // array of trigger pointers for downstream reactions through port NQueens.manager.do_work
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &nqueens_manager_self[src_runtime]->base.allocations); 
                nqueens_manager_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)] and NQueens.workers.do_work(0,20).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 20, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range NQueens.workers.do_work(0,20).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 1, 20 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 20; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    // Point to destination port NQueens.workers.do_work's trigger struct.
                    nqueens_manager_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_workers_self[dst_runtime]->_lf__do_work;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range NQueens.manager.finished(0,1)->[NQueens.runner.finish(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 1 of NQueens.manager triggers 1 downstream reactions
            // through port NQueens.manager.finished.
            nqueens_manager_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 1 of NQueens.manager, allocate an
            // array of trigger pointers for downstream reactions through port NQueens.manager.finished
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &nqueens_manager_self[src_runtime]->base.allocations); 
            nqueens_manager_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges NQueens.manager.finished(0,1)->[NQueens.runner.finish(0,1)] and NQueens.runner.finish(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range NQueens.runner.finish(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port NQueens.runner.finish's trigger struct.
                nqueens_manager_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_runner_self[dst_runtime]->_lf__finish;
            }
        }
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 20, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int src_channel = range_mr.digits[0]; // Channel index.
                int src_bank = range_mr.digits[1]; // Bank index.
                // Reaction 2 of NQueens.manager triggers 1 downstream reactions
                // through port NQueens.manager.do_work.
                nqueens_manager_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of NQueens.manager, allocate an
                // array of trigger pointers for downstream reactions through port NQueens.manager.do_work
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &nqueens_manager_self[src_runtime]->base.allocations); 
                nqueens_manager_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)] and NQueens.workers.do_work(0,20).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 20, 1 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range NQueens.workers.do_work(0,20).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 1, 20 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 20; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    // Point to destination port NQueens.workers.do_work's trigger struct.
                    nqueens_manager_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_workers_self[dst_runtime]->_lf__do_work;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    
    // **** End of non-nested deferred initialize for NQueens.manager
    // **** Start non-nested deferred initialize for NQueens.workers
    
    // For reference counting, set num_destinations for port NQueens.workers.solutions_found.
    // Iterate over range NQueens.workers.solutions_found(0,20)->[NQueens.manager.solutions_found(0,20)].
    {
        int range_start[] =  { 0, 0 };
        int range_radixes[] = { 1, 20 };
        int permutation[] = { 0, 1 };
        mixed_radix_int_t range_mr = {
            2,
            range_start,
            range_radixes,
            permutation
        };
        for (int range_count = 0; range_count < 0 + 20; range_count++) {
            int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
            int src_channel = range_mr.digits[0]; // Channel index.
            int src_bank = range_mr.digits[1]; // Bank index.
            nqueens_workers_self[src_runtime]->_lf_solutions_found.num_destinations = 1;
            mixed_radix_incr(&range_mr);
        }
    }
    // For reference counting, set num_destinations for port NQueens.workers.more_work.
    // Iterate over range NQueens.workers.more_work(0,20)->[NQueens.manager.more_work(0,20)].
    {
        int range_start[] =  { 0, 0 };
        int range_radixes[] = { 1, 20 };
        int permutation[] = { 0, 1 };
        mixed_radix_int_t range_mr = {
            2,
            range_start,
            range_radixes,
            permutation
        };
        for (int range_count = 0; range_count < 0 + 20; range_count++) {
            int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
            int src_channel = range_mr.digits[0]; // Channel index.
            int src_bank = range_mr.digits[1]; // Bank index.
            nqueens_workers_self[src_runtime]->_lf_more_work.num_destinations = 1;
            mixed_radix_incr(&range_mr);
        }
    }
    {
        int triggers_index[20] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range NQueens.workers.solutions_found(0,20)->[NQueens.manager.solutions_found(0,20)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 1, 20 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int src_channel = range_mr.digits[0]; // Channel index.
                int src_bank = range_mr.digits[1]; // Bank index.
                // Reaction 0 of NQueens.workers triggers 1 downstream reactions
                // through port NQueens.workers.solutions_found.
                nqueens_workers_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of NQueens.workers, allocate an
                // array of trigger pointers for downstream reactions through port NQueens.workers.solutions_found
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &nqueens_workers_self[src_runtime]->base.allocations); 
                nqueens_workers_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        // Iterate over range NQueens.workers.more_work(0,20)->[NQueens.manager.more_work(0,20)].
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 1, 20 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int src_channel = range_mr.digits[0]; // Channel index.
                int src_bank = range_mr.digits[1]; // Bank index.
                // Reaction 0 of NQueens.workers triggers 1 downstream reactions
                // through port NQueens.workers.more_work.
                nqueens_workers_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of NQueens.workers, allocate an
                // array of trigger pointers for downstream reactions through port NQueens.workers.more_work
                trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                        1, sizeof(trigger_t*),
                        &nqueens_workers_self[src_runtime]->base.allocations); 
                nqueens_workers_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                mixed_radix_incr(&range_mr);
            }
        }
        for (int i = 0; i < 20; i++) triggers_index[i] = 0;
        // Iterate over ranges NQueens.workers.solutions_found(0,20)->[NQueens.manager.solutions_found(0,20)] and NQueens.manager.solutions_found(0,20).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 1, 20 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range NQueens.manager.solutions_found(0,20).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 20, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 20; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    // Point to destination port NQueens.manager.solutions_found's trigger struct.
                    nqueens_workers_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_manager_self[dst_runtime]->_lf__solutions_found;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
        for (int i = 0; i < 20; i++) triggers_index[i] = 1;
        // Iterate over ranges NQueens.workers.more_work(0,20)->[NQueens.manager.more_work(0,20)] and NQueens.manager.more_work(0,20).
        {
            int src_start[] =  { 0, 0 };
            int src_value[] =  { 0, 0 }; // Will be incremented.
            int src_radixes[] = { 1, 20 };
            int src_permutation[] = { 0, 1 };
            mixed_radix_int_t src_range_mr = {
                2,
                src_value,
                src_radixes,
                src_permutation
            };
            // Iterate over range NQueens.manager.more_work(0,20).
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 20, 1 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 20; range_count++) {
                    int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    int dst_channel = range_mr.digits[0]; // Channel index.
                    int dst_bank = range_mr.digits[1]; // Bank index.
                    int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                    int src_channel = src_range_mr.digits[0]; // Channel index.
                    int src_bank = src_range_mr.digits[1]; // Bank index.
                    // Point to destination port NQueens.manager.more_work's trigger struct.
                    nqueens_workers_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &nqueens_manager_self[dst_runtime]->_lf__more_work;
                    mixed_radix_incr(&src_range_mr);
                    if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                        // Start over with the source.
                        for (int i = 0; i < src_range_mr.size; i++) {
                            src_range_mr.digits[i] = src_start[i];
                        }
                    }
                    mixed_radix_incr(&range_mr);
                }
            }
        }
    }
    
    // **** End of non-nested deferred initialize for NQueens.workers
    // **** End of non-nested deferred initialize for NQueens
    // Connect inputs and outputs for reactor NQueens.
    // Connect inputs and outputs for reactor NQueens.runner.
    // Connect NQueens.runner.start(0,1)->[NQueens.manager.start(0,1)] to port NQueens.manager.start(0,1)
    // Iterate over ranges NQueens.runner.start(0,1)->[NQueens.manager.start(0,1)] and NQueens.manager.start(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range NQueens.manager.start(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            nqueens_manager_self[dst_runtime]->_lf_start = (manager_start_t*)&nqueens_runner_self[src_runtime]->_lf_start;
        }
    }
    // Connect inputs and outputs for reactor NQueens.manager.
    // Connect NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)] to port NQueens.workers.do_work(0,20)
    // Iterate over ranges NQueens.manager.do_work(0,20)->[NQueens.workers.do_work(0,20)] and NQueens.workers.do_work(0,20).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 20, 1 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range NQueens.workers.do_work(0,20).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 1, 20 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int dst_channel = range_mr.digits[0]; // Channel index.
                int dst_bank = range_mr.digits[1]; // Bank index.
                int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                int src_channel = src_range_mr.digits[0]; // Channel index.
                int src_bank = src_range_mr.digits[1]; // Bank index.
                nqueens_workers_self[dst_runtime]->_lf_do_work = (worker_do_work_t*)&nqueens_manager_self[src_runtime]->_lf_do_work[src_channel];
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    // Connect NQueens.manager.finished(0,1)->[NQueens.runner.finish(0,1)] to port NQueens.runner.finish(0,1)
    // Iterate over ranges NQueens.manager.finished(0,1)->[NQueens.runner.finish(0,1)] and NQueens.runner.finish(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range NQueens.runner.finish(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            nqueens_runner_self[dst_runtime]->_lf_finish = (benchmarkrunner_finish_t*)&nqueens_manager_self[src_runtime]->_lf_finished;
        }
    }
    // Connect inputs and outputs for reactor NQueens.workers.
    // Connect NQueens.workers.solutions_found(0,20)->[NQueens.manager.solutions_found(0,20)] to port NQueens.manager.solutions_found(0,20)
    // Iterate over ranges NQueens.workers.solutions_found(0,20)->[NQueens.manager.solutions_found(0,20)] and NQueens.manager.solutions_found(0,20).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 1, 20 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range NQueens.manager.solutions_found(0,20).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 20, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int dst_channel = range_mr.digits[0]; // Channel index.
                int dst_bank = range_mr.digits[1]; // Bank index.
                int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                int src_channel = src_range_mr.digits[0]; // Channel index.
                int src_bank = src_range_mr.digits[1]; // Bank index.
                nqueens_manager_self[dst_runtime]->_lf_solutions_found[dst_channel] = (manager_solutions_found_t*)&nqueens_workers_self[src_runtime]->_lf_solutions_found;
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    // Connect NQueens.workers.more_work(0,20)->[NQueens.manager.more_work(0,20)] to port NQueens.manager.more_work(0,20)
    // Iterate over ranges NQueens.workers.more_work(0,20)->[NQueens.manager.more_work(0,20)] and NQueens.manager.more_work(0,20).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 1, 20 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range NQueens.manager.more_work(0,20).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 20, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 20; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                int dst_channel = range_mr.digits[0]; // Channel index.
                int dst_bank = range_mr.digits[1]; // Bank index.
                int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                int src_channel = src_range_mr.digits[0]; // Channel index.
                int src_bank = src_range_mr.digits[1]; // Bank index.
                nqueens_manager_self[dst_runtime]->_lf_more_work[dst_channel] = (manager_more_work_t*)&nqueens_workers_self[src_runtime]->_lf_more_work;
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 20) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    {
        {
            // Add action NQueens.runner.nextIteration to array of is_present fields.
            _lf_is_present_fields[0] 
                    = &nqueens_runner_self[0]->_lf_nextIteration.is_present;
        }
        {
            // Add action NQueens.runner.done to array of is_present fields.
            _lf_is_present_fields[1] 
                    = &nqueens_runner_self[0]->_lf_done.is_present;
        }
    }
    {
        {
            // Add action NQueens.manager.next to array of is_present fields.
            _lf_is_present_fields[2] 
                    = &nqueens_manager_self[0]->_lf_next.is_present;
        }
        {
            // Add action NQueens.manager.done to array of is_present fields.
            _lf_is_present_fields[3] 
                    = &nqueens_manager_self[0]->_lf_done.is_present;
        }
    }
    // Reactor is a bank. Iterate over bank members.
    for (int nqueens_workers_i = 0; nqueens_workers_i < 20; nqueens_workers_i++) {
    }
    {
        int count = 0;
        {
            // Add port NQueens.runner.start to array of is_present fields.
            _lf_is_present_fields[4 + count] = &nqueens_runner_self[0]->_lf_start.is_present;
            count++;
        }
    }
    {
        int count = 0;
        {
            // Add port NQueens.manager.do_work to array of is_present fields.
            // Port NQueens.manager.do_work is a multiport. Iterate over its channels.
            for (int nqueens_manager_do_work_c = 0; nqueens_manager_do_work_c < 20; nqueens_manager_do_work_c++) {
                _lf_is_present_fields[5 + count] = &nqueens_manager_self[0]->_lf_do_work[nqueens_manager_do_work_c].is_present;
                count++;
            }
            // Add port NQueens.manager.finished to array of is_present fields.
            _lf_is_present_fields[5 + count] = &nqueens_manager_self[0]->_lf_finished.is_present;
            count++;
        }
    }
    {
        int count = 0;
        // Reactor is a bank. Iterate over bank members.
        for (int nqueens_workers_i = 0; nqueens_workers_i < 20; nqueens_workers_i++) {
            // Add port NQueens.workers.solutions_found to array of is_present fields.
            _lf_is_present_fields[26 + count] = &nqueens_workers_self[nqueens_workers_i]->_lf_solutions_found.is_present;
            count++;
            // Add port NQueens.workers.more_work to array of is_present fields.
            _lf_is_present_fields[26 + count] = &nqueens_workers_self[nqueens_workers_i]->_lf_more_work.is_present;
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance NQueens
    {
        //levels.size() == 1
        nqueens_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        nqueens_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        
        // Set reaction priorities for ReactorInstance NQueens.runner
        {
            //levels.size() == 1
            nqueens_runner_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_runner_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
            //levels.size() == 1
            nqueens_runner_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_runner_self[0]->_lf__reaction_1.index = 0x7fffffffffff0001LL;
            //levels.size() == 1
            nqueens_runner_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_runner_self[0]->_lf__reaction_2.index = 0x7fffffffffff0004LL;
            //levels.size() == 1
            nqueens_runner_self[0]->_lf__reaction_3.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_runner_self[0]->_lf__reaction_3.index = 0x7fffffffffff0005LL;
        }
        
        
        // Set reaction priorities for ReactorInstance NQueens.manager
        {
            //levels.size() == 1
            nqueens_manager_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_manager_self[0]->_lf__reaction_0.index = 0x7fffffffffff0002LL;
            //levels.size() == 1
            nqueens_manager_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_manager_self[0]->_lf__reaction_1.index = 0x7fffffffffff0003LL;
            //levels.size() == 1
            nqueens_manager_self[0]->_lf__reaction_2.chain_id = 1;
            // index is the OR of level 4 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_manager_self[0]->_lf__reaction_2.index = 0x7fffffffffff0004LL;
            //levels.size() == 1
            nqueens_manager_self[0]->_lf__reaction_3.chain_id = 1;
            // index is the OR of level 6 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_manager_self[0]->_lf__reaction_3.index = 0x7fffffffffff0006LL;
            //levels.size() == 1
            nqueens_manager_self[0]->_lf__reaction_4.chain_id = 1;
            // index is the OR of level 7 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_manager_self[0]->_lf__reaction_4.index = 0x7fffffffffff0007LL;
        }
        
        
        // Set reaction priorities for ReactorInstance NQueens.workers
        // Reactor is a bank. Iterate over bank members.
        for (int nqueens_workers_i = 0; nqueens_workers_i < 20; nqueens_workers_i++) {
            //levels.size() == 1
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 5 and 
            // deadline 140737488355327 shifted left 16 bits.
            nqueens_workers_self[nqueens_workers_i]->_lf__reaction_0.index = 0x7fffffffffff0005LL;
        }
        
    }
    
    
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            #ifdef MODAL_REACTORS
            if (!_lf_mode_is_active(_lf_startup_reactions[i]->mode)) {
                // Mode is not active. Remember to trigger startup when the mode
                // becomes active.
                _lf_startup_reactions[i]->mode->should_trigger_startup = true;
                continue;
            }
            #endif
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {

    // Return true if there are shutdown reactions.
    return (_lf_shutdown_reactions_size > 0);
}
void terminate_execution() {}
