// Code generated by the Lingua Franca compiler from:
// file://Users/shaokai/git/lingua-franca/test/C/src/TimeLimit.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/Users/shaokai/git/lingua-franca/test/C/src-gen/TimeLimit"
#include "ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
// =============== START reactor class Clock
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} clock_y_t;
typedef struct {
    struct self_base_t base;
    interval_t offset;
    interval_t period;
    int count;
    clock_y_t _lf_y;
    int _lf_y_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
} clock_self_t;
#include "ctarget/set.h"
void clockreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    clock_self_t* self = (clock_self_t*)instance_args;
    clock_y_t* y = &self->_lf_y;
    #pragma GCC diagnostic pop
    (self->count)++;
    //printf("Reacting at time %ld.\n", lf_time_logical_elapsed());
    lf_set(y, self->count);
        
}
#include "ctarget/set_undef.h"
clock_self_t* new_Clock() {
    clock_self_t* self = (clock_self_t*)_lf_new_reactor(sizeof(clock_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = clockreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__t.last = NULL;
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class Clock

// =============== START reactor class Destination
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
    lf_token_t* token;
    int length;
    void (*destructor) (void* value);
    void* (*copy_constructor) (void* value);
} destination_x_t;
typedef struct {
    struct self_base_t base;
    
    int s;
    destination_x_t* _lf_x;
    // width of -2 indicates that it is not a multiport.
    int _lf_x_width;
    // Default input (in case it does not get connected)
    destination_x_t _lf_default__x;
    reaction_t _lf__reaction_0;
    reaction_t _lf__reaction_1;
    trigger_t _lf__shutdown;
    reaction_t* _lf__shutdown_reactions[1];
    trigger_t _lf__x;
    reaction_t* _lf__x_reactions[1];
} destination_self_t;
#include "ctarget/set.h"
void destinationreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    destination_self_t* self = (destination_self_t*)instance_args;
    destination_x_t* x = self->_lf_x;
    int x_width = self->_lf_x_width;
    #pragma GCC diagnostic pop
    // printf("%d\n", x->value);
    if (x->value != self->s) {
        printf("Error: Expected %d and got %d.\n", self->s, x->value);
        exit(1);
    }
    self->s++;
        
}
#include "ctarget/set_undef.h"
#include "ctarget/set.h"
void destinationreaction_function_1(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    destination_self_t* self = (destination_self_t*)instance_args;
    
    #pragma GCC diagnostic pop
    printf("**** shutdown reaction invoked.\n");
    if (self->s != 10000002) {
        fprintf(stderr, "ERROR: Expected 10000002 but got %d.\n", self->s);
        exit(1);
    }
    lf_print("Approx. time per reaction: %lldns", lf_time_physical_elapsed()/(self->s+1));
        
}
#include "ctarget/set_undef.h"
destination_self_t* new_Destination() {
    destination_self_t* self = (destination_self_t*)_lf_new_reactor(sizeof(destination_self_t));
    // Set input by default to an always absent default input.
    self->_lf_x = &self->_lf_default__x;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = destinationreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__reaction_1.number = 1;
    self->_lf__reaction_1.function = destinationreaction_function_1;
    self->_lf__reaction_1.self = self;
    self->_lf__reaction_1.deadline_violation_handler = NULL;
    self->_lf__reaction_1.STP_handler = NULL;
    self->_lf__reaction_1.name = "?";
    self->_lf__reaction_1.mode = NULL;
    self->_lf__shutdown_reactions[0] = &self->_lf__reaction_1;
    self->_lf__shutdown.last = NULL;
    self->_lf__shutdown.reactions = &self->_lf__shutdown_reactions[0];
    self->_lf__shutdown.number_of_reactions = 1;
    self->_lf__shutdown.is_timer = false;
    self->_lf__x.last = NULL;
    self->_lf__x_reactions[0] = &self->_lf__reaction_0;
    self->_lf__x.reactions = &self->_lf__x_reactions[0];
    self->_lf__x.number_of_reactions = 1;
    self->_lf__x.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Destination

// =============== START reactor class TimeLimit
typedef struct {
    struct self_base_t base;
    interval_t period;
    
    reaction_t _lf__reaction_0;
    trigger_t _lf__stop;
    reaction_t* _lf__stop_reactions[1];
} timelimit_self_t;
#include "ctarget/set.h"
void timelimitreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    timelimit_self_t* self = (timelimit_self_t*)instance_args;
    
    #pragma GCC diagnostic pop
    request_stop();
        
}
#include "ctarget/set_undef.h"
timelimit_self_t* new_TimeLimit() {
    timelimit_self_t* self = (timelimit_self_t*)_lf_new_reactor(sizeof(timelimit_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = timelimitreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__stop.last = NULL;
    self->_lf__stop_reactions[0] = &self->_lf__reaction_0;
    self->_lf__stop.reactions = &self->_lf__stop_reactions[0];
    self->_lf__stop.number_of_reactions = 1;
    self->_lf__stop.is_timer = true;
    return self;
}
// =============== END reactor class TimeLimit

void _lf_set_default_command_line_options() {}
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[2];
int _lf_timer_triggers_size = 2;
// Array of pointers to shutdown triggers.
reaction_t* _lf_shutdown_reactions[1];
int _lf_shutdown_reactions_size = 1;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 1;
    _lf_is_present_fields = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) lf_print_error_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    
    _lf_startup_reactions = (reaction_t**)calloc(0, sizeof(reaction_t*));
    _lf_startup_reactions_size = 0;
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    timelimit_self_t* timelimit_self[1];
    clock_self_t* timelimit_c_self[1];
    destination_self_t* timelimit_d_self[1];
    // ***** Start initializing TimeLimit of class TimeLimit
    timelimit_self[0] = new_TimeLimit();
    int bank_index = 0;
    timelimit_self[0]->period = USEC(1);
    // Initializing timer TimeLimit.stop.
    timelimit_self[0]->_lf__stop.offset = SEC(10);
    timelimit_self[0]->_lf__stop.period = 0;
    _lf_timer_triggers[_lf_timer_triggers_count++] = &timelimit_self[0]->_lf__stop;
    timelimit_self[0]->_lf__stop.mode = NULL;
    
    {
        // ***** Start initializing TimeLimit.c of class Clock
        timelimit_c_self[0] = new_Clock();
        int bank_index = 0;
        timelimit_c_self[0]->offset = 0;
        timelimit_c_self[0]->period = timelimit_self[0]->period;
        // width of -2 indicates that it is not a multiport.
        timelimit_c_self[0]->_lf_y_width = -2;
        { // For scoping
            static int _initial = 0;
            timelimit_c_self[0]->count = _initial;
        } // End scoping.
        // Initializing timer TimeLimit.c.t.
        timelimit_c_self[0]->_lf__t.offset = 0;
        timelimit_c_self[0]->_lf__t.period = USEC(1);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &timelimit_c_self[0]->_lf__t;
        timelimit_c_self[0]->_lf__t.mode = NULL;
        
        //***** End initializing TimeLimit.c
    }
    {
        // ***** Start initializing TimeLimit.d of class Destination
        timelimit_d_self[0] = new_Destination();
        int bank_index = 0;
        // width of -2 indicates that it is not a multiport.
        timelimit_d_self[0]->_lf_x_width = -2;
        _lf_shutdown_reactions[_lf_shutdown_reactions_count++] = &timelimit_d_self[0]->_lf__reaction_1;
        { // For scoping
            static int _initial = 1;
            timelimit_d_self[0]->s = _initial;
        } // End scoping.
        
        //***** End initializing TimeLimit.d
    }
    //***** End initializing TimeLimit
    
    // **** Start deferred initialize for TimeLimit
    {
        
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of TimeLimit.
        timelimit_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0;
        }
        
        // ** End initialization for reaction 0 of TimeLimit
        
        // **** Start deferred initialize for TimeLimit.c
        {
            
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of TimeLimit.c.
            timelimit_c_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            timelimit_c_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &timelimit_c_self[0]->base.allocations);
            timelimit_c_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &timelimit_c_self[0]->base.allocations);
            timelimit_c_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &timelimit_c_self[0]->base.allocations);
            {
                int count = 0;
                {
                    timelimit_c_self[0]->_lf__reaction_0.output_produced[count++] = &timelimit_c_self[0]->_lf_y.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of TimeLimit.c
            
        }
        // **** End of deferred initialize for TimeLimit.c
        // **** Start deferred initialize for TimeLimit.d
        {
            
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of TimeLimit.d.
            timelimit_d_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 0 of TimeLimit.d
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of TimeLimit.d.
            timelimit_d_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0;
            }
            
            // ** End initialization for reaction 1 of TimeLimit.d
            
        }
        // **** End of deferred initialize for TimeLimit.d
    }
    // **** End of deferred initialize for TimeLimit
    // **** Start non-nested deferred initialize for TimeLimit
    
    
    
    // **** Start non-nested deferred initialize for TimeLimit.c
    
    // For reference counting, set num_destinations for port TimeLimit.c.y.
    // Iterate over range TimeLimit.c.y(0,1)->[TimeLimit.d.x(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        timelimit_c_self[src_runtime]->_lf_y.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range TimeLimit.c.y(0,1)->[TimeLimit.d.x(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 0 of TimeLimit.c triggers 1 downstream reactions
            // through port TimeLimit.c.y.
            timelimit_c_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of TimeLimit.c, allocate an
            // array of trigger pointers for downstream reactions through port TimeLimit.c.y
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &timelimit_c_self[src_runtime]->base.allocations); 
            timelimit_c_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges TimeLimit.c.y(0,1)->[TimeLimit.d.x(0,1)] and TimeLimit.d.x(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range TimeLimit.d.x(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port TimeLimit.d.x's trigger struct.
                timelimit_c_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &timelimit_d_self[dst_runtime]->_lf__x;
            }
        }
    }
    
    // **** End of non-nested deferred initialize for TimeLimit.c
    // **** Start non-nested deferred initialize for TimeLimit.d
    
    
    
    
    // **** End of non-nested deferred initialize for TimeLimit.d
    // **** End of non-nested deferred initialize for TimeLimit
    // Connect inputs and outputs for reactor TimeLimit.
    // Connect inputs and outputs for reactor TimeLimit.c.
    // Connect TimeLimit.c.y(0,1)->[TimeLimit.d.x(0,1)] to port TimeLimit.d.x(0,1)
    // Iterate over ranges TimeLimit.c.y(0,1)->[TimeLimit.d.x(0,1)] and TimeLimit.d.x(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range TimeLimit.d.x(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            timelimit_d_self[dst_runtime]->_lf_x = (destination_x_t*)&timelimit_c_self[src_runtime]->_lf_y;
        }
    }
    // Connect inputs and outputs for reactor TimeLimit.d.
    {
    }
    {
    }
    {
        int count = 0;
        {
            // Add port TimeLimit.c.y to array of is_present fields.
            _lf_is_present_fields[0 + count] = &timelimit_c_self[0]->_lf_y.is_present;
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance TimeLimit
    {
        //levels.size() == 1
        timelimit_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        timelimit_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        
        // Set reaction priorities for ReactorInstance TimeLimit.c
        {
            //levels.size() == 1
            timelimit_c_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            timelimit_c_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        }
        
        
        // Set reaction priorities for ReactorInstance TimeLimit.d
        {
            //levels.size() == 1
            timelimit_d_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            timelimit_d_self[0]->_lf__reaction_0.index = 0x7fffffffffff0001LL;
            //levels.size() == 1
            timelimit_d_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 140737488355327 shifted left 16 bits.
            timelimit_d_self[0]->_lf__reaction_1.index = 0x7fffffffffff0002LL;
        }
        
    }
    
    reaction_t **_lf_reaction_instances = (reaction_t**) calloc(4, sizeof(reaction_t*));
    _lf_reaction_instances[0] = &timelimit_self[0]->_lf__reaction_0;
    _lf_reaction_instances[1] = &timelimit_c_self[0]->_lf__reaction_0;
    _lf_reaction_instances[2] = &timelimit_d_self[0]->_lf__reaction_0;
    _lf_reaction_instances[3] = &timelimit_d_self[0]->_lf__reaction_1;
    // Initialize the scheduler
    size_t num_reactions_per_level[3] = 
        {2, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 3,
                            .reaction_instances = _lf_reaction_instances};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {

}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }
}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    for (int i = 0; i < _lf_shutdown_reactions_size; i++) {
        if (_lf_shutdown_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_shutdown_reactions[i], -1);
        }
    }
    // Return true if there are shutdown reactions.
    return (_lf_shutdown_reactions_size > 0);
}
void terminate_execution() {}
